### ISSUE TITLE
Adding commit to dependency PR

### ISSUE THREAD

**Issue by marcovc** [ryanhiebert/probot-chain#4]
Hi,

Thanks for you package. I have a question:

Say I have a PR2 that is based on a PR1. When reviewing PR1 someone adds a commit to it, and then merges it. Would this extension still work in this case?

Thanks!

**Comment by ryanhiebert** [comment]
PR2 wouldn't contain that change, but if PR1 is already merged, the change won't be lost. The PR2 branch could be rebased on top of the revised PR1. It works the way git does.

I've been interested to see some solution to the issue of keeping dependent branches up to date with situations like this. In git, not just GitHub. If you come across a nice way, I'd be happy to hear about it

**Comment by marcovc** [comment]
I guess my question is if this tool would change the base of PR2 to the new commit added to PR1 automatically.

I found this helpful,  but you probably already know about it: https://wchargin.github.io/posts/managing-dependent-pull-requests/

**Comment by ryanhiebert** [comment]
I had not seen that yet. I think that this can be complementary to that, since he mentions the pain if updating pull request bases.

I'm interested to see if there's something to build on that kind of workflow that could handle trees of changes well.

**Comment by marcovc** [comment]
> I think that this can be complementary to that

That was what I thought!

**Comment by ryanhiebert** [comment]
Here's a few interesting links about stacked patches with git and github. It's an interesting area to me, and I figured you might like the links as well. If you find other resources, or have other ideas, please share. Figuring out how to do this well is a strong interest of mine, and is a big part of the reason I created probot-chain in the first place.

https://github.com/ezyang/ghstack
http://events17.linuxfoundation.org/sites/events/files/slides/An%20Introduction%20to%20Stacked%20Git.pdf
https://www.systutorials.com/docs/linux/man/1-stg/

**Comment by ryanhiebert** [comment]
One more: TopGit: https://mackyle.github.io/topgit/topgit.html

**Comment by ryanhiebert** [comment]
I think that there is a place for a tool that can manage more complex pull request dependencies, but I don't think that chain is or will be the right place to do it. I do think that such a tool would end up being a *replacement* for probot-chain, and not merely augment it.
